### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by malkes** [kigen/bitbucket-pipelines-android#5]
Hi, first of all, thanks for sharing the scripts. 

Do you have some examples using cache from docker and android sdk?

**Comment by kigen** [comment]
I don't have any examples at the moment. 
Let me check if I can hack it as part of the examples here.

**Comment by diegosurita** [comment]
You can add docker on the "services" and "caches" section of the pipline's step, like the example bellow.
```yaml
// ...
- step:
    services:
      - docker
    caches:
      - docker
    script:
// ...
```

Documentation link: https://confluence.atlassian.com/bitbucket/run-docker-commands-in-bitbucket-pipelines-879254331.html
